### ISSUE TITLE
Blank auto generated 'Review Date' in grey box

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/topcat#101]
E.g. http://topcat/app/#/editor/4b1f3fa5-7092-49f6-adcd-80c45dd22421

**Comment by GMDuncan** [comment]
What column in the import csv (if any) is used to populate this field in topcat? All MEHS habitat maps that I've checked so far are very odd...

**Comment by sumothecat** [comment]
Review date column was not mapped for MESH. We will need to issue a batch update if you'd like a review date? I'll create a new issue to deal with "empty" review dates better in the UI.

**Comment by sumothecat** [comment]
I'll just mention @GMDuncan to make sure you get pinged with this question!

**Comment by GMDuncan** [comment]
I'm happy with leaving it blank if it's allowed, I wasn't sure whether it was mandatory or not. Could always use import date as review date if so? (assuming it's the review date for the metadata and not the data!) @helen-ellwood

**Comment by LynnHeeley** [comment]
review date is not auto filled. required behaviour in place
