### ISSUE TITLE
Date picker pops up automatically on temporal extent

### ISSUE THREAD

**Issue by felixMasonJncc** [jncc/topcat#115]
This is irritating for end users if they intend to type or paste the date in

**Comment by sumothecat** [comment]
I don't know why we have date pickers at all. They are completely useless for any scenario in the application. Suggest resolve by removing them, and if possible whatever js library they come from.

**Comment by sumothecat** [comment]
This is more urgent since this is currently broken. http://localhost:55466/app/#/editor/679434f5-baab-47b9-98e4-81c8e3a1a6f9 - the TemporalExtent box dates are just wrong.
