### ISSUE TITLE
Tidy up Publications Catalogue keywords

### ISSUE THREAD

**Issue by sumothecat** [jncc/topcat#118]
Trim punctuation (and any whitespace) from keywords e.g `surveillance.`

**Comment by sumothecat** [comment]
Should not have keywords that are the same string as the title
`Sustaining a Living Wales` http://topcat-beta/app/#/editor/14717d40-05d2-46e8-a7c5-ade1f3ab4a8c

**Comment by felixMasonJncc** [comment]
Keywords now generated from page hierachy
