### ISSUE TITLE
Change security terms to ‘OFFICIAL’ and ‘OFFICIAL-SENSITIVE’

### ISSUE THREAD

**Issue by sumothecat** [jncc/topcat#139]
Mary has asked for this to be in line with the Information Management policy.

**Comment by MaryCampling** [comment]
You may want to future-proof it with the option 'SECRET' in there too.

**Comment by ulric-wilson** [comment]
This request re-iterated in meeting with JNCC Comms w.r.t publications

**Comment by sumothecat** [comment]
Done. Using Raven Studio patching.
