### ISSUE TITLE
Basic validation of mesh-gui vocab

### ISSUE THREAD

**Issue by GMDuncan** [jncc/topcat#146]
With the change of the *mesh-gui* keyword to a freetext to enable values to be added by the user themselves as new habitat maps arrive, it would be beneficial to add a basic validation to prevent the user entering a **definitely invalid** GUI.

The validation should check that the entered value matches the following exactly:
2 upper case characters followed by 6 digits.

Validation to check for entry of guis already in use (and warn rather than prevent as there may be legitimate reasons for re-use...) would be handy, but I'm aware that this would require significantly more work!

**Comment by sumothecat** [comment]
done in 2aded4ba6faabf21998a1ca3b88ab5bfe5012326
