### ISSUE TITLE
Providing users with links to Data Provider Agreements and License

### ISSUE THREAD

**Issue by GMDuncan** [jncc/topcat#147]
For third party data, the Marine team is working towards the use of a _'Data Provider Agreement'_ which will capture specific restrictions information on the dataset as requested by the original owner/supplier. The aim is for this procedure to be rolled out across JNCC's marine team (and potentially JNCC-wide) in the coming months.

Whilst restrictions can be captured generally in the _usage_ section of the metadata, it would be worthwhile to have a standard place for metadata creators to link to the DPA for the dataset in question for auditing and information etc.

This doesn't necessarily have to be a new field, but could instead be written into the topcat/metadata protocol to instruct the user to include the information in an existing field (e.g. the Notes section).

**Comment by SoniaKhela** [comment]
Discuss if Notes box is adequate for this

**Comment by LynnHeeley** [comment]
covered by #51 and #52
