### ISSUE TITLE
Formatting is unescaped in tsv output

### ISSUE THREAD

**Issue by GMDuncan** [jncc/topcat#149]
When exporting metadata searches as tsv, fields containing formatting (newline, tabs etc) are not retained within quotes or other escape characters. 

This causes problems when viewing the exported records, as fields containing either tabs or linebreaks cause data to be shifted. 

Formatting is commonly used in the large text fields such as abstract and lineage.

**Comment by GMDuncan** [comment]
Problem seems to lie in Excel's importing of tsv's through the open dialogue box...

**Comment by sumothecat** [comment]
Need to revisit this general issue - we should be able to provide a  CSV that opens directly in Excel for usability.
