### ISSUE TITLE
Topcat search errors on search terms with # in. ie. Markdown headings

### ISSUE THREAD

**Issue by ulric-wilson** [jncc/topcat#154]
The Abstract editor uses Markdown with syntax for headings being ## for H2, ### for H3 etc.  but these terms cannot be searched for.  Entering ## into search raises and error message.

**Comment by sumothecat** [comment]
Why are you needing to search for '###Title' ? I wouldn't expect the Lucene search engine to support this.

**Comment by ulric-wilson** [comment]
Because the abstract fields contain markdown headings in atx format for publications – prefixed with hash characters to denote heading level.  I was trying to find all publications that had '#### Comment' in them.

**Comment by sumothecat** [comment]
That's unlikely to ever be supported due to the way Lucence works. It's not impossible of course but would require special customization. Unless there's a real need that can't be worked around I'm going to close this as Won't Fix. Hope that's ok.
