### ISSUE TITLE
Build process does not cleanly deploy, leaves old site elements in situ.

### ISSUE THREAD

**Issue by felixMasonJncc** [jncc/topcat#161]
The build process does not cleanly deploy the application. It leaves elements that have been removed from the solution in the output folder.

Ie. The ingest page has been removed. This change has been deployed to beta. However topcat-beta/#/app/ingest still exists. The view / angular controller are still in the beta folder.

There should be an option in Temcity to clear the output folder on build.

**Comment by sumothecat** [comment]
Not priority.
