### ISSUE TITLE
Sort options for search results

### ISSUE THREAD

**Issue by ulric-wilson** [jncc/topcat#162]
User request from Luke / Cathy - ordering of search results is unclear.  User request for alphabetical  sort.

**Comment by CathyJinJNCC** [comment]
This was brought up again by Luke recently

Luke: "Record Sort - The ability to sort Topcat record search results by title/tag/date, etc. (but especially by Title) – Something that is sorely missing and a lot of colleagues ask about… (this would be joint top of the list)"

**Comment by SoniaKhela** [comment]
Is this closed now

**Comment by CathyJinJNCC** [comment]
Yep
