### ISSUE TITLE
Exact search terms

### ISSUE THREAD

**Issue by sumothecat** [jncc/topcat#163]
From Mike: 
I was trying to search for data from a specific survey, which as you know all have unique identifiers. When I searched for this one (CEND0812) the results come back for all records with CEND in them, which obviously isn’t that useful. Is there a way of either making the searches more specific, or restricting the search to a particular keyword field (as the survey code is a keyword)?

We should support exact terms, for example `"CEND0812"`.

**Comment by CathyJinJNCC** [comment]
Suspect this is being affected by the "OR" bug (https://github.com/jncc/topcat/issues/156). It seems to work for simple cases

**Comment by CathyJinJNCC** [comment]
[Topcat exact search terms sbe.xlsx](https://github.com/jncc/topcat/files/1407930/Topcat.exact.search.terms.sbe.xlsx)
