### ISSUE TITLE
Ability to search by distribution format

### ISSUE THREAD

**Issue by GMDuncan** [jncc/topcat#164]
Several colleagues have asked for the ability to search by particular data type / distribution formats. Specifically to filter/search to show only records concerning geospatial data.

**Comment by CathyJinJNCC** [comment]
Graeme - do you only need this at the group level granularity? i.e. "Database", "Image", "Spreadsheet", etc or the specific file type as well, e.g. shapefile

**Comment by GMDuncan** [comment]
As far as I'm aware I think the original request was for the specific type (e.g. "Geospatial (vector polygon)" or "Comma Separated Values (csv)").

However, I think that filtering by the group (Document, Geospatial, Spreadsheet) is probably actually more useful, at least to begin with, as it removes the requirement for the user to know the specific document type (or Select all of them to default).

I suppose both could be useful in the long run, but start with Groups?

**Comment by CathyJinJNCC** [comment]
Sounds good, thank you :)

**Comment by SoniaKhela** [comment]
Expand Groups in Advanced Search options - e.g.
Data type     Data format
Database      xls, csv, .dmb
Geospatial    vector polygon, raster polygon
Document   word, pdf, txt
Image
Audio
Video
Powerpoint

**Comment by CathyJinJNCC** [comment]
Sonia could you create a new issue for searching by specific data formats if you haven't already? Thanks.

Data format filtering by group has been done and deployed but I just realised the UI doesn't let you do a search with no search terms, will look into it.

**Comment by CathyJinJNCC** [comment]
Deployed fix for above so now you can search just with data format. Closing this issue now, feel free to reopen if it's not right.
