### ISSUE TITLE
As a dataset manager I would like an extra separate field to add my name as the dataset manager and be able to search for my own records.  

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#208]
Currently we're using a point of contact in the Gemini metadata but this is published as Open Data. A separate way of storing internal points of contact may also be needed. The workaround is to populate this in the notes section but this doesn't allow for reporting.

**Comment by SoniaKhela** [comment]
Add a field for who created the record

**Comment by CathyJinJNCC** [comment]
Looks like I might be able to do this this sprint

**Comment by GMDuncan** [comment]
Considering (in marine at least) that dataset managers are in constant flux due to recruitment etc, would it be possible to tie this to post rather than a specific name? would help with currency issues and save having to update when a post is refilled!

**Comment by CathyJinJNCC** [comment]
Short: Yes.

Long: Current plan is to allow two optional fields for name and email which are free text fields (same as we already have). The only solid use case at the moment is to then allow the name to be searchable, so I don't see why you can't put a post instead of an actual name. :) You'd have to remember to search for the post though.

**Comment by CathyJinJNCC** [comment]
Deployed

**Comment by CathyJinJNCC** [comment]
Reopening this for some tweaking after discussion with Pete, mainly changing "internal contact" to "manager" to make it dataset manager specific.
