### ISSUE TITLE
As a Topcat user, I want to be able to create records tied to a non-file resource (i.e. URL)

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#230]

**Comment by paul-gilbertson** [comment]
Sounds about right

**Comment by CathyJinJNCC** [comment]
[topcat wider resources sbe.xlsx](https://github.com/jncc/topcat/files/1454606/topcat.wider.resources.sbe.xlsx)

Are we allowing multi line connection strings?

**Comment by paul-gilbertson** [comment]
No, I would say not

**Comment by CathyJinJNCC** [comment]
Leaving this open for a discussion about database connection string security
