### ISSUE TITLE
As a topcat user, I want to be able to add more than one resource locator URL to a record

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#231]

**Comment by SoniaKhela** [comment]
low priority as workaround available

**Comment by CathyJinJNCC** [comment]
Similar to https://github.com/jncc/topcat/issues/313 Keeping it open because this one is talking about URLs and 313 talks about file resources.

**Comment by CathyJinJNCC** [comment]
The fields in the new publishing tab accept URLs and filepaths so closing this now
