### ISSUE TITLE
As a Topcat user, I want to publish my cloud hosted dataset as Open Data in Topcat

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#233]
Provide proper support for URLs. At the moment to publish a record to DGU you need a filepath even if that file doesn't get uploaded.

**Comment by SoniaKhela** [comment]
is this a datahub issue?

**Comment by CathyJinJNCC** [comment]
Not required but will probably affect it if it's done.

**Comment by LynnHeeley** [comment]
complete
