### ISSUE TITLE
As a Topcat user, I want the DOI to be included in the Gemini

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#243]

**Comment by CathyJinJNCC** [comment]
May be a good idea to hold off on this until Gemini 2.3 is implemented, which includes a new field to formally record DOIs. https://www.agi.org.uk/about/resources/category/81-gemini?download=129:gemini-changes-2-2-to-2-3

**Comment by sumothecat** [comment]
Duplicates #311
