### ISSUE TITLE
As a Topcat user I need new keywords to be added

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#250]
Opening this issue to keep track of the new keywords being added.

**Comment by CathyJinJNCC** [comment]
[Topcat keyword requests.zip](https://github.com/jncc/topcat/files/1513187/Topcat.keyword.requests.zip)

**Comment by SoniaKhela** [comment]
Keywords to add as requested by John Henson Webb 06/12/17

JNCC Category:
CITES

Seabird Season:
Over-wintering
Wildfowl
raptors 
Seabirds at Sea

MESH GUI:
MESH

Publication category:
Acidification
NVC 
National Vegetation Classification
Peatland
Cetacean
Peat bog
NBN
Wildfowl
Seabirds at Sea


Keywords already exist / no vocab - Assign vocabulary to Publication category / Delete duplicates 

SSSI 
sssi - delete duplicate (and replace records with SSSI)
reef 
Coral reef 
SPA 	
SAC	
Fish		
Pesticides	
GIS		 
Predation	
Raptors	 – delete duplicate (and replace records with raptors)
raptors 
Natura 2000	
Water Framework Directive (change from: water frame directive)
Survey	
Seabed

**Comment by CathyJinJNCC** [comment]
Edited above comment with changes, leaving the ones that already exist to deal with another day
