### ISSUE TITLE
As a marine reference dataset manager I would like Topcat to have the functionality to ingest data from other metadata catalogues preferably via xml 

### ISSUE THREAD

**Issue by SoniaKhela** [jncc/topcat#258]
Requested by Eleanor Manca. check if xml can be converted to csv as that functionality already exists

**Comment by SoniaKhela** [comment]
Investigate the need for this requirement further in line with third party data

**Comment by LynnHeeley** [comment]
Probably worthwhile closing and investing effort elsewhere. I think the idea would be e.g. MEDIN metadata could be harvested, but this could be manually achieved for now and revisited if the need is identified again later.
