### ISSUE TITLE
Search module rejects certain characters 'oops an error has occurred' when search string contains these characters

### ISSUE THREAD

**Issue by SoniaKhela** [jncc/topcat#266]
it is unlikely for anyone to search using these characters alone (eg. (marine) does not generate error but () does.

!
--
#
(
)
+
-
:
<
>
[
\
]
^
{
}
~

**Comment by owenboswarva** [comment]
As far as I can tell any of the following characters produce an oops error when entered in the search box, with or without other text: !#()+-:<>[\]^{}~ though as Sonia points out ( and ) separated by other text doesn't produce an error.

None of these characters produce the error:  "$%&'*,./ ;=?@_`|

It does seem unlikely anyone will search for these characters in isolation. However some of them appear in existing dataset titles which may be used for searches.

**Comment by sumothecat** [comment]
Thanks for the bug report. The cost of improving this is considerable and it's highly unlikely we will ever improve this, so I'm closing it for now. The issue will remain searchable. If users report having a real problem then it can be reopened.

**Comment by SoniaKhela** [comment]
Hi Pete

That’s fine its not a priority
