### ISSUE TITLE
Add Earth Observation to JNCC Category

### ISSUE THREAD

**Issue by SoniaKhela** [jncc/topcat#288]

**Comment by sumothecat** [comment]
Just to clarify, we need a new JNCC Category called `Earth Observation` ?

**Comment by SoniaKhela** [comment]
Hi Pete

Yes – there is no where for terrestrial habitat mapping and also I want to get the EO team to start adding records to Topcat so need everything set up to go.

The other Vocabulary list we need to resolve is the Species list. Apparently Cathy says there are no keywords in that list. Should it be a comprehensive list to import of broad taxa groups (.e. butterfly, moth, caterpillar, larvae, bird, mammal) or actual species level common names which I don’t think is necessary. I would go with the broad one.

Sonia

**Comment by sumothecat** [comment]
New category `Earth Observation` added.
