### ISSUE TITLE
As Topcat Manager I would like the Meta contact name to be included in Search so records can be searched for specific teams (internal)

### ISSUE THREAD

**Issue by SoniaKhela** [jncc/topcat#294]

**Comment by sumothecat** [comment]
Is this necessary for GDPR - if so, how?

**Comment by SoniaKhela** [comment]
this is medium priority for enhanced search not for gdpr - can remove from sprint 9. 
But if you search for records with your name in meta contact via search box it does not find names. Only way is by exporting records. If personal data is included in a record it should be searchable. However we are doing a batch update to remove names so this may not be relevant
