### ISSUE TITLE
Remove person contact from XML published to Data.gov.uk

### ISSUE THREAD

**Issue by owenboswarva** [jncc/topcat#295]
The responsible organisation email field and the point of contact fields (on the Meta tab) in Topcat sometimes contain personal data and may also become out of date quickly.

Please make a change to Topcat so that the values in these fields are no longer populated in the relevant fields in the XML when the Topcat record is published to Data.gov.uk.

(For purposes of user enquiries DGU will display default values from JNCC's publisher details.)

**Comment by owenboswarva** [comment]
This approach has been approved by Paul. 

If the values are mandatory we can used "Digital and Data Solutions, JNCC" for the point of contact name and "data@jncc.gov.uk" for both email fields.

**Comment by sumothecat** [comment]
This seems fine to me - I'll implement it.

**Comment by PeteMontgomery** [comment]
Setting:
MetadataPointOfContact.Email = 'data@jncc.gov.uk'
MetadataPointOfContact.Name = 'Joint Nature Conservation Committee'
as opposed to 'Digital & Data Solutions' because that's the standard we used for other records, and the team name has a tendency to change! ;-)

**Comment by owenboswarva** [comment]
I would rather stick with "Digital and Data Solutions, JNCC" as requested, to help build profile.

Have we established that the fields cannot be left blank when the metadata is submitted to DGU? Blank would be better because there's a default inherited from the admin interface in DGU.

**Comment by PeteMontgomery** [comment]
I haven't looked at whether the fields can be left blank. It would be fairly easy to establish - upload a gemini document and see? Do you have one you can use? I haven't used the new GDU. 

I've altered the name to 'Digital and Data Solutions, JNCC'. Please reopen if any probs.

**Comment by owenboswarva** [comment]
Hi, I need to reopen issue this unfortunately. Having reviewed the original request we also need the "responsible organisation email" field blanked (or defaulted to data@jncc.gov.uk). Thank you.
