### ISSUE TITLE
Copy some updated data files into http://data.jncc.gov.uk/data/

### ISSUE THREAD

**Issue by owenboswarva** [jncc/topcat#296]
I will be redacting some data from a large number of data files that are currently stored in http://data.jncc.gov.uk/data/ for access from Data.gov.uk.

Once this work is complete I will need developer assistance to replace the existing files with the updated files. Sometime in mid-May would be ideal. Thank you.

**Comment by CathyJinJNCC** [comment]
To create the new files you should be able to just clear out the current published URL, make sure the filepath is pointing to the new file, then republish. A dev would then need to go on the server and delete the old file I think.

**Comment by CathyJinJNCC** [comment]
Hmm, I guess that's fine if you don't mind the filenames being the same. If publishing is still broken when we do this then that will have to be the solution.

**Comment by owenboswarva** [comment]
Yes, there's no need for any change to the filenames. To be clear this issue has not been raised for any Topcat work per se; it's just an operation that needs to be carried out by someone with admin access to the http://data.jncc.gov.uk/data/ folder.

**Comment by CathyJinJNCC** [comment]
This is done now so closing
