### ISSUE TITLE
Bulk update OGL v2 to OGL v3

### ISSUE THREAD

**Issue by owenboswarva** [jncc/topcat#297]
Please update all references to Open Government Licence v2.0 in the Use Constraints field in Topcat to Open Government Licence v3.0.

The material differences between these licences are very minor, but v3.0 has been the latest version of the OGL for a number of years and publishing data under v2.0 will reduce its interoperability with other open datasets.

Please check with me before doing this; the OGL v2 references are in a number of different formats so it's probably easier if I provide a CSV listing the affected records and the new text for the Use Constraints field.

**Comment by CathyJinJNCC** [comment]
This is done now. Only issue was the limitations on public access couldn't be blank so I changed those to "None" as discussed.
