### ISSUE TITLE
Bulk update invalid local file share paths

### ISSUE THREAD

**Issue by owenboswarva** [jncc/topcat#298]
Discussed briefly. I will provide a CSV with the Topcat ID, old path value, new path value. This operation is a follow-up to issue #296 for purposes of tidying up the record keeping in Topcat. #296 does not depend on this operation, so this issue can be treated as less urgent / done later on.

**Comment by sumothecat** [comment]
Is this necessary for GDPR? And @owenboswarva is the CSV ready?

**Comment by CathyJinJNCC** [comment]
Can probably do this with #327
