### ISSUE TITLE
As Topcat Manager I wish to replace all personal names and emails from 'Meta contact' with team names / emails. via bulk upload (internal)

### ISSUE THREAD

**Issue by SoniaKhela** [jncc/topcat#299]
Spreadsheet almost ready with what to replace with.

**Comment by sumothecat** [comment]
@SoniaKhela if you give me a ping when this is ready I'll implement.

**Comment by CathyJinJNCC** [comment]
@PeteMontgomery I'll take the batch update issues off your hands so you can get to the raven upgrade faster

**Comment by PeteMontgomery** [comment]
Merci beaucoup @CathyJinJNCC !  👍

**Comment by CathyJinJNCC** [comment]
Done now.
