### ISSUE TITLE
Republish all open data published records 

### ISSUE THREAD

**Issue by SoniaKhela** [jncc/topcat#300]
when issues #298, #295, #296 & #297 resolved. Owen has IAO Sign Off approval - batch republish by 25 May 2018. 
Sonia has emailed all reference dataset managers to let them know this is happening and if there are any records which have had changes to not republish. **Check with Sonia first before completing this.**

**Comment by owenboswarva** [comment]
#298 ("Bulk update invalid local file share paths") doesn't need to be resolved before #300 is actioned. (I probably won't get to #298 before 25 May so don't wait for it please.)

**Comment by CathyJinJNCC** [comment]
We should do this sooner rather than later because of the backlog issues on DGU's side (I wonder if they're because of GDPR...).

**Comment by owenboswarva** [comment]
I'll try to produce the list for #297 today.

**Comment by CathyJinJNCC** [comment]
If we can get the #297, #299, and #298 changes all into one spreadsheet by tomorrow then I can potentially do one update for all of these. I know #298 isn't a priority but if it's ready then might as well include it.

**Comment by owenboswarva** [comment]
#298 won't be ready; lots of work to do as the internal copies of the data files aren't in the right places yet. #299 is up to Sonia but #300 isn't dependent on it.

**Comment by SoniaKhela** [comment]
To confirm this is to implement the change Pete made in Issue #295 Remove person contact from XML published to Data.gov.uk by republishing all records again using my name as IAO sign off.

**Comment by CathyJinJNCC** [comment]
1389 records went through the uploader and are currently waiting to be picked up by DGU.

Issues:
Gemini validation
- Blank responsible organisation roles (12 records), these all had the name as JNCC so I changed the role to "custodian" which is what similar datasets were using. Example: 8935a9f1-2c5f-4296-b014-42e4233b7d9e
- Incorrect bounding box values (2 records), corrected these using the values Owen provided. Example: http://topcat/app/#/editor/dae4ed66-c967-4d37-825c-bd33cd650d92
Read only records (872 records), removed the read only flag from these as discussed. Example: http://topcat/app/#/editor/dae4ed66-c967-4d37-825c-bd33cd650d92

**Comment by CathyJinJNCC** [comment]
Another issue: there are some records on Topcat which have "hidden" resources which can't be seen by the user, these are added to the XML and go all the way through to DGU but resulted in dead links because the data wasn't uploaded. Owen has provided me a list of all currently working links from a DGU dump which I have updated the Topcat records with so that all links on DGU should now be working.

**Comment by CathyJinJNCC** [comment]
All records have been harvested by DGU. I think there's still an issue with the enquiries contact details which I've brought up with Ross from DGU. Also those records with hidden resources need to have those resources properly added into the Topcat record either in the path or resource locator field.

**Comment by owenboswarva** [comment]
Thanks Cathy. I'll look at the records with multiple resources; some now point to landing pages on the JNCC site, which is fine, but others might need zipping up and republishing. There are a few other issues I need to look at with the records but the GDPR issues are sorted I think. (The issue with the enquiries contact details is irritating but doesn't involve any publication of personal details so isn't urgent.)
