### ISSUE TITLE
Multiple / alternative resources design (UI)

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/topcat#313]
Current design involves having one internal path/field, and multiple "publishable resource" fields.

Questions:
- [ ] Can Gemini support multiple file types for the multiple resources?
- [ ] We currently have a search filter on the data type, should we extend this to include the publishable resources?
- [ ] Should we create a data patch to retroactively add publishable resources for already published records?

![Whiteboard_2018-11-30_123500.png](https://images.zenhubusercontent.com/596f7cf061b4ca3b0a74fdc5/843d053a-55a5-4810-9403-8227e923a21b)

![Whiteboard_2018-12-10_135818.png](https://images.zenhubusercontent.com/596f7cf061b4ca3b0a74fdc5/cca32235-33bd-4658-8908-ea27a9f1d3a1)

**Comment by CathyJinJNCC** [comment]
Potentially can design this with image support (https://github.com/jncc/topcat/issues/314) in mind

**Comment by LynnHeeley** [comment]
1 field and then option to add further ones. needs a limit to maximum number

**Comment by LynnHeeley** [comment]
timeboxed file picker investigation

**Comment by PeteMontgomery** [comment]
I'm toying with the name of **publication packages** for this feature. 'Multiple resources' and 'Alternative resources' are hopelessly confusing names. 

> A resource may optionally have a _publication package_ - a set of files that will be published instead of the working copy.

Simples.
