### ISSUE TITLE
As a Topcat user I want to publish records to the Datahub showing the metadata only

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#316]

**Comment by SoniaKhela** [comment]
Has a decision been made if the 'publish to datahub' fields will be separate to the open data status

**Comment by PeteMontgomery** [comment]
We think it will look like the same button, i.e. it will all be controlled in one place, both Open Data / DGU and Datahub. We've got a design meeting when Cathy's back.

**Comment by SoniaKhela** [comment]
Ok can I sit in on that please?
Same design is ok but as long as it’s a separate field will make our lives a lot easier.

😊

**Comment by PeteMontgomery** [comment]
From our dev discussions a couple of weeks ago it was looking like it makes sense to be integrated. 

Why do you think it will make things easier to be a separate field? You could create a mockup to show what you mean. Forwarded you the invite for if you want to join the dev discussion.

**Comment by CathyJinJNCC** [comment]
I think she means a separate Topcat attribute as they (Sonia and Owen) use csv exports to look at all the records, so it would be useful for them to have an easy way to distinguish between datahub published, open data published etc. (Currently you can't easily use the export to determine the open data status shown on the record page, so Owen's had fun and games trying to rederive it from the various timestamps)

**Comment by PeteMontgomery** [comment]
That's a good use case to consider - how easy it is to see the status in an export.

**Comment by CathyJinJNCC** [comment]
Will forward the meeting invite to Owen too in case he wants to join

**Comment by CathyJinJNCC** [comment]
We decided this wasn't needed anymore as you can publish records without resources if needed
