### ISSUE TITLE
Document session architecture for publishing 

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/topcat#325]
the RavenDB document session is a Unit of Work. We shouldn't have this:

    store.Conventions.MaxNumberOfRequestsPerSession = 1000;

We need to change the lifecycle/scope of the document session in the open data publishing code so that it is short-lived. "Per-record publish" is probably correct.

**Comment by LynnHeeley** [comment]
Cathy suggested that this was complete - is that correct?
