### ISSUE TITLE
Migrate current live data to new live database

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/topcat#337]

**Comment by CathyJinJNCC** [comment]
Gone through with Chris on what needs to be done to change the DNS host for topcat. He's assigned another IP to the Topcat-Dev server which I've assigned to the beta site in IIS so that it doesn't need to be accessed via a port.

**Comment by CathyJinJNCC** [comment]
Migration done, follow up task is to decom the old jncc-topcat server
