### ISSUE TITLE
Fix migration issues

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/topcat#338]
Prioritise issues and create tickets

- [x] NGram searching
- [ ] CSV/TSV exports
- [ ] Phrase queries
- [ ] Ninject extensions
- [ ] Spinning thing to wait for stale indexes
- [ ] Elmah?
- [ ] Go through and review "raven4" comments

**Comment by CathyJinJNCC** [comment]
Separated out into #339, #340, and #341
