### ISSUE TITLE
Raven4 migration tech debt

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#341]
- [x] Ninject extensions plugin - look into reimplementing this
- [x] Elmah - commented out, do we still need it?
- [ ] Query listeners - commented out, do we still need it?
- [ ] Versioning and spatial tests - ignored, do we still need them?
- [x] Go through and review "raven4" comments - lots of commented code that needs tidying
- [x] Update all nuget package versions

**Comment by LynnHeeley** [comment]
Do ninject, raven4 comments and elmah
