### ISSUE TITLE
Rename Path to WorkingCopy (Topcat data structure)

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#347]
This is a nicety and probably not required. Rename Path to something that implies it is the working version of the dataset.

**Comment by PeteMontgomery** [comment]
There's no need to change the implementation name of this - a significant amount of work compares with any benefit. In any event the field is still a Path - we're just clarifying the semantics; i.e. _which_ path.

In the UI, the user sees the field as `Location` anyway in the input placeholder. I've change this to `Working copy location`. Also updates the tooltip help to explain that this is the working copy.
