### ISSUE TITLE
Updates to the current publishing logic to support the new multiple resources data structure

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#351]
The current publishing workflow needs to work with the new multi resource data structure. The unit tests need updating and then should pass. The Robot will also need changing.

- Validate that there is at least one publishable resource provided before publishing
- Use only one publishable resource for publishing (the first one?)
- If the resource is a URL, use that value in the Gemini and do nothing else
- If the resource is a file path, upload the data to data.jncc.gov.uk and update the "external locator" field with the data.jncc.gov.uk URL

**Comment by LynnHeeley** [comment]
subsumed into larger publishing ticket
