### ISSUE TITLE
Additional use cases for new publication workflow (Darwin Plus)

### ISSUE THREAD

**Issue by owenboswarva** [jncc/topcat#357]
This is a request for additions to the planned new publication workflow for (a) publication of a Data.gov.uk page with a link to a data file or landing page *other than* the landing page on the Datahub, and (b) publication of a Data.gov.uk page *without* any resource link.

Recent discussions with LH and CJ refer.

Background: 

The T&Cs for Darwin Plus projects require grantees to publish or make available all project outputs as open data and list them on Data.gov.uk. The publication requirements http://jncc.defra.gov.uk/page-7614 state that if no suitable existing data platforms exist or the grantee is otherwise unable to publish the data, the grantee shall provide all data and associated metadata to JNCC for archiving and publication. We understand from the BES team that JNCC has agreed this with Defra.

The standard expectation is a record on Data.gov.uk with a resource link to the data or to a landing page, which may be on a non-JNCC site. The arrangements do not contemplate publication on JNCC's Datahub, although that may be reasonable if JNCC is publishing both the data and the metadata. If JNCC is only setting up the record on Data.gov.uk then the resource link from that record should naturally point to the external landing page or data location provided by the grantee. There may also be cases where a Data.gov.uk page is required without a resource link at all, for example when an output has been produced but is under embargo.

If we want to fully accommodate these requirements in Topcat, the publication workflow will need additional requirements for (a) publication of a Data.gov.uk page with a link to a data file or landing page *other than* the landing page on the Datahub, and (b) publication of a Data.gov.uk page *without* any resource link.

This is a recent example of a published Darwin Plus record:

http://topcat/app/#/editor/f604e973-b98d-497d-8a14-1d3903985df1
https://data.gov.uk/dataset/f2272490-823e-47d4-944b-1eeef9234ddc/darwinplus053-northern-rockhopper-penguin-eudyptes-moseleyi-tdr-data-from-nightingale-island-tristan-da-cunha-2016

We don't have any firm idea of how often JNCC will be required to publish Darwin Plus data or metadata as this depends on whether grantees comply with the T&Cs and/or make their own arrangements. There are about 70 Darwin Plus projects, some of which are ongoing.

**Comment by CathyJinJNCC** [comment]
This is done
