### ISSUE TITLE
Publishing policy

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/topcat#359]
Capture and implement a pure function like:

    GetPublishingPolicyResult(Record) : PublishingPolicyResult

where

    class PublishingPolicyResult {
        DatahubRecord:    bool
        DatahubResources: string[]
        DguRecord:        bool
        DguResources:     string[]
        HelpfulMessage:   string    
    }

**Comment by CathyJinJNCC** [comment]
Adding enough logic to show a result in the UI for now

**Comment by CathyJinJNCC** [comment]
Closing as this isn't needed anymore
