### ISSUE TITLE
Document manual delete process (dgu and hub) incl knowledge share

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/topcat#370]

**Comment by mattdebont** [comment]
Delete exists for Hub, but we don't have an unpublish workflow as such from Topcat

**Comment by CathyJinJNCC** [comment]
Created wiki page "How to manually delete from the Datahub" with steps on how to delete from the database, elasticsearch, Topcat, and the data server. Had knowledge share with rest of the devs.
