### ISSUE TITLE
'Unpublishable' status is confusing

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/topcat#379]
Small note: When I came back to look at the Publishing demo last week I found that the 'Unpublishable' status was confusing / ambiguous. 

Does it mean that 

- the record is not publishable, or
- it's possible to unpublish the record?

As an analogy, 

>    Doable | Undoable

does not mean the same as

>    Doable | Not doable

Is there any reason why the status can't just be `Not publishable`?

@CathyJinJNCC ❓

**Comment by CathyJinJNCC** [comment]
Yep you're right. It's a hangover from back when we didn't really have enough space to use "Not publishable" and I just went ahead and used the same text. I agree it's a lot clearer to say "Not publishable" so I'll change it to that (will close this and incorporate it into my UI tweaks issue #376 )
