### ISSUE TITLE
Force fail large files in Topcat Robot uploader

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#380]
If the file is above 1GB, don't allow publishing so that we can manually handle it

**Comment by mattdebont** [comment]
Is 1GB too much? only indexing pdf files at present so should be fine still as long as we don't pass 1GB pdf's into the index

**Comment by CathyJinJNCC** [comment]
Sticking to 1GB - this check is for the upload of files to data.jncc.gov.uk, if we need another check for the PDFs for indexing we can create another ticket
