### ISSUE TITLE
Test the manual mechanism to publish metadata only still works

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#382]
Publishing from the Topcat Robot can be triggered manually and can be given a "metadata only" flag which simply means it will skip the method that uploads files to data.jncc.gov.uk. This means any metadata around those files (friendly names, URLs, file sizes, file extensions) will still be sent as usual, and for indexing, the encoded file contents are also still sent.

**Comment by mattdebont** [comment]
We know it won't work with the new search indexing code, need to figure out the resource hub side of this

**Comment by CathyJinJNCC** [comment]
Because of the changes to publishing (multiple resources, addition of friendly names), the resources shown on the DGU pages may potentially be incorrect (e.g. a change in the friendly name will be published even though the file may not be updated to match that change). In addition, for the ResourceHub there is a risk that the search results will be updated with the new file contents.

However this is still quite low risk as it's dev triggered and will usually only be used for republishing. Owen is willing to accept the risk of these small changes so there is no coding to be done here.

**Comment by mattdebont** [comment]
This publishing option will not be available with the new infrastructure
