### ISSUE TITLE
Make Topcat vocab/keyword search less terrible

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#397]
Examples of weird search behaviour from Luke:

Deep-Sea Muds
I have to type “Deep-Se” to retrieve this; a single letter more or less will not return a result.  “Muds” also works.
So the following does not work “Mud”, “Deep”, “Deep-sea”, Deep-sea Mud”, etc.

Southern North Sea SAC
Pasting “Southern North Sea” will not work, only having ‘Southern’ works.  Once you start typing ‘North’ it replaces the retrieved tags with irrelevant ones

Ocean quahog
Typing in “Ocean” beforehand doesn’t help.  Need to enter at least “quah” before the search is returned

As said in the email, the risk is that users can't find keywords and end up creating their own deviations

**Comment by CathyJinJNCC** [comment]
Returning all keyword results now and not just top 10 which I think fixes the bottom two issues, the hyphen search will need further looking at

**Comment by LynnHeeley** [comment]
see also realted ticket #340
