### ISSUE TITLE
Publishing workflow - allow IAOs to reject records

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#414]
IAOs can only sign off records at the moment. We should consider letting them reject records to clearly indicate that the record is not ready for publishing and to remove them from the publishing approvals list. This may require fundamental changes to the workflow.

**Comment by jonparsonsjncc** [comment]
adding a note to record takes item from list
ulric to discuss with Lynn

**Comment by CathyJinJNCC** [comment]
Seems like we don't need this anymore so closing
