### ISSUE TITLE
Remove files that are no longer part of publishing package

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/topcat#417]
It is possibly easier now after Cathy's recent change to store data on data.jncc.gov.uk in a folder-per-record to delete the data files that are removed from a Topcat record. This should be done so we don't have orphaned records sitting around which shouldn't be there.

question - should this file be removed from the google index as part of the process

if so we need to add google search console to data.gov.uk

**Comment by jonparsonsjncc** [comment]
see attached file which needs adding to the root of data.jncc.gov.uk
to allow search console to verify ownership
[https://app.zenhub.com/files/12618306/a9d1dd3b-1e31-4255-b309-66b5047c3864/download](https://app.zenhub.com/files/12618306/a9d1dd3b-1e31-4255-b309-66b5047c3864/download)
need to unzip and upload the html

**Comment by CathyJinJNCC** [comment]
Google file upload done.

Current thinking on an approach for this:
1. Move existing folder (if exists) to non web accessible location
2. Upload new files (if any) to new folder
3. Publish to hub
4. Publish to DGU
5. Clean up old folder (if exists)

Roll back:
1. Delete new folder (if exists)
2. Move back old folder

Also need to think about how to remove from Google search index (notify Jon to manually remove or look for an API?)

**Comment by jonparsonsjncc** [comment]
analytics complete and data studio report created

https://datastudio.google.com/reporting/1fxM3MaxDI8KMBOSur0FOf10dOz9vrko4/page/WyBv

**Comment by jonparsonsjncc** [comment]
implementing 0 and 5
