### ISSUE TITLE
Test the unpublish process. 

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/topcat#418]
Follow the steps in the wiki entry made by Cathy to test that unpublishing can happen and that we can respond in an emergency.

also include process for removing entry in google search index using google search console
this will also needs to be done for the files in data hub

**Comment by felixMasonJncc** [comment]
Tested the instructions here on beta

http://jncc-wiki/index.php?title=Restricted_Access_Pages/JNCC_website%2C_Resource_hub%2C_and_microsites/How_to_manually_delete_from_the_Datahub

They worked

Yay
