### ISSUE TITLE
Nest Programme Leaders group under InformationAssetOwners

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/topcat#423]
Suspect this wasn't done because Topcat wasn't seeing the nested groups as being part of the group.

**Comment by CathyJinJNCC** [comment]
Nesting the PL group seems to work but we should test again to double check.

**Comment by ulric-wilson** [comment]
I can still see the approvals page in TC and link at top of homepage - Ulli

Ulric Wilson
Co-Team Leader, Digital and Data Solutions
Tel: 01733 866853, Mob: 07741 901730
