### ISSUE TITLE
Add google tag manager

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/topcat#424]
Pleas add this code to all pages in top cat - so we can then add analytics and report on traffic

Install Google Tag Manager
Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PTQL32L');</script>

Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PTQL32L"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by CathyJinJNCC** [comment]
Deployed to beta

**Comment by jonparsonsjncc** [comment]
Happy for you to push to live as no way of testing if works on beta

As long as beta is still working correctly with code in it then it should be OK

Jon

**Comment by CathyJinJNCC** [comment]
You can use http://topcat-beta.green.jncc.gov.uk?
