### ISSUE TITLE
Must validate the file path!

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/topcat#80]
Need to check that it's an actual path. It's too important to be wrong. Can't remember exactly how far I got with this attempting to do it "live" - which I think is the right way to do it (separate from the RecordValidator)

**Comment by SoniaKhela** [comment]
is this similar to #169 ?

**Comment by LynnHeeley** [comment]
no different to #169. this is a nice to have and has not proved to be an issue - particularly as the filepath is the working copy now rather than the published path (which does error on trying to publish.)
